---
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - management
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values:
                - cluster-autoscaler
        topologyKey:
          - "kubernetes.io/hostname"
          - "topology.kubernetes.io/zone"
          - "topology.kubernetes.io/region"
          - "*"

autoDiscovery:
  clusterName:  CLUSTER_NAME
  tags:
  - k8s.io/cluster-autoscaler/enabled
  - k8s.io/cluster-autoscaler/{{ .Values.autoDiscovery.clusterName }}

awsRegion: ap-northeast-2
cloudConfigPath: /etc/aws.conf
cloudProvider: aws

containerSecurityContext:
  capabilities:
    drop:
    - ALL

# dnsPolicy -- Defaults to `ClusterFirst`. Valid values are:
# `ClusterFirstWithHostNet`, `ClusterFirst`, `Default` or `None`.
# If autoscaler does not depend on cluster DNS, recommended to set this to `Default`.
dnsPolicy: ClusterFirst

expanderPriorities: {}
  # 10:
  #   - .*p2-node-group.*
  # 50:
  #   - .*p3-node-group.*

extraArgs:
  logtostderr: true
  stderrthreshold: info
  v: 4
  # write-status-configmap: true
  # leader-elect: true
  skip-nodes-with-local-storage: false
  expander: least-waste
  # scale-down-enabled: true
  balance-similar-node-groups: true
  # min-replica-count: 0
  # scale-down-utilization-threshold: 0.5
  # scale-down-non-empty-candidates-count: 30
  # max-node-provision-time: 15m0s
  # scan-interval: 10s
  # scale-down-delay-after-add: 10m
  # scale-down-delay-after-delete: 0s
  # scale-down-delay-after-failure: 3m
  # scale-down-unneeded-time: 10m
  skip-nodes-with-system-pods: false

extraEnv: {}
extraEnvConfigMaps: {}
envFromConfigMap: ""

extraVolumes:
  - name: ssl-certs
    hostPath:
      path: /etc/ssl/certs/ca-bundle.crt

extraVolumeMounts:
  - name: ssl-certs
    mountPath: /etc/ssl/certs/ca-certificates.crt
    readOnly: true

fullnameOverride: RELEASE_NAME

image: {}

podAnnotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  kubernetes.io/psp: RELEASE_NAME

podDisruptionBudget:
  minAvailable: 1

priorityClassName: "system-cluster-critical"

rbac:
  create: true
  pspEnabled: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: IAM_ROLE_NAME
    create: true
    name: SERVICE_ACCOUNT
    automountServiceAccountToken: true

replicaCount: 1

resources:
  limits:
    cpu: 100m
    memory: 300Mi
  requests:
    cpu: 100m
    memory: 300Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  runAsGroup: 1001

# service:
#   annotations: {}
#   labels: {}
#   externalIPs: []
#   loadBalancerIP: ""
#   loadBalancerSourceRanges: []
#   servicePort: 8085
#   portName: http
#   type: ClusterIP

serviceMonitor:
  enabled: true
  interval: 10s
  namespace: monitoring
  selector:
    release: prometheus-operator
  path: /metrics

prometheusRule:
  enabled: true
  additionalLabels: {}
  # prometheusRule.namespace -- Namespace which Prometheus is running in.
  namespace: monitoring
  interval: null
  rules: []

tolerations:
  - key: dedicated
    operator: Equal
    value: 'management'
    effect: NoSchedule
