apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: efs-csi-controller-pdb
  namespace: kube-system
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: efs-csi-controller
