global:
  edition: GITLAB_EDITION
  hosts:
    domain: DOMAIN
    https: false
  ingress:
    configureCertmanager: false
    tls:
      enabled: false
  # shell:
  #   tcp:
  #     proxyProtocol: true


nginx-ingress:
  controller:
    # config:
      # use-forwarded-headers: "true"
      # X-Forwarded-Ssl: "on"
      # X-Forwarded-Proto: http
      # proxy-real-ip-cidr: 10.2.0.0/16  # The VPC CIDR, to be trusted
      # use-proxy-protocol: "true"       # Tell NGINX to Expect ProxyProtocol headers
    service:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
        # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
        service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
        service.beta.kubernetes.io/aws-load-balancer-scheme: LOAD_BALANCE_INTERNAL
        service.beta.kubernetes.io/aws-load-balancer-ssl-ports: 443
        service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ACM_ARN
        service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
        service.beta.kubernetes.io/aws-load-balancer-type: 'nlb-ip'
      targetPorts:
        https: http

gitlab-runner:
  install: GITLAB_RUNNER_INSTALL
  runners:
    privileged: true
certmanager:
  install: false