provider: aws

aws:
  region: "REGION"
  # zoneType: public, private
  zoneType: "ZONETYPE"
  apiRetries: 3
  batchChangeSize: 1000
  ## AWS Zone tags
  ##
  zoneTags: []
  evaluateTargetHealth: "true"

sources:
  # - crd
  - service
  - ingress
  # - contour-httpproxy

domainFilters: [DOMAINS]
excludeDomains: []
triggerLoopOnEvent: false
policy: upsert-only
registry: "txt"
# txtPrefix: ""
# txtSuffix: ""
txtOwnerId: "HOSTZONEID"

replicas: 1

podAffinityPreset: "soft"
podAntiAffinityPreset: "soft"

nodeAffinityPreset:
  type: "soft"
  key: "role"
  values:
    - management

tolerations:
  - key: dedicated
    operator: Equal
    value: "management"
    effect: NoSchedule

## Additional labels for the pod(s).
##
podLabels: {}

priorityClassName: "system-cluster-critical"

crd:
  create: false
  apiversion: ""
  kind: ""

service:
  enabled: true
  type: ClusterIP
  port: 7979
  # nodePort:
  # clusterIP: ""
  # externalIPs: []
  # loadBalancerIP:
  ## Address that are allowed when svc is LoadBalancer
  loadBalancerSourceRanges: []
  ## https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  annotations: {}

  ## Provide any additional labels which may be required. This can be used to
  ## have external-dns show up in `kubectl cluster-info`
  ##  kubernetes.io/cluster-service: "true"
  ##  kubernetes.io/name: "external-dns"
  labels: {}

serviceAccount:
  create: true
  name: SERVICE_ACCOUNT
  annotations:
    eks.amazonaws.com/role-arn: IAM_ROLE_ARN
  automountServiceAccountToken: true

rbac:
  create: true
  clusterRole: true
  apiVersion: v1
  pspEnabled: false

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: ["ALL"]

podSecurityContext:
  fsGroup: 1001
  runAsUser: 1001
  # runAsNonRoot: true

resources:
 limits:
   memory: 50Mi
 requests:
   memory: 50Mi
   cpu: 10m

podDisruptionBudget:
  minAvailable: 1

## Prometheus Exporter / Metrics
metrics:
  enabled: false
  # podAnnotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "7979"

  ## Prometheus Operator ServiceMonitor configuration
  serviceMonitor:
    enabled: false
    # namespace: monitoring
    # interval: 10s
    # selector:
    #   prometheus: my-prometheus