kind: ServiceAccount
apiVersion: v1
metadata:
  name: SERVICE_ACCOUNT
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/instance: RELEASE_NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: RELEASE_NAME
    helm.sh/chart: RELEASE_NAME-CHART_VERSION
  annotations:
    eks.amazonaws.com/role-arn: 'IAM_ROLE_ARN'
    meta.helm.sh/release-name: RELEASE_NAME
    meta.helm.sh/release-namespace: NAMESPACE
