apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ebs-snapshot-controller-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: ebs-snapshot-controller
