---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: gp3
parameters:
  type: gp3
  fsType: ext4 # AWS default: ext4
  # encrypted: false # volume encrypt with kms (default: false)
  # kmsKeyId: arn:aws:kms:us-west-2:111122223333:alias/ExampleAlias
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: io2
parameters:
  type: io2
  iopsPerGB: "500"
  fsType: ext4 # AWS default: ext4
  # encrypted: false # volume encrypt with kms (default: false)
  # kmsKeyId: arn:aws:kms:us-west-2:111122223333:alias/ExampleAlias
provisioner: ebs.csi.aws.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer