fullnameOverride: RELEASE_NAME

resources: {}
  # limits:
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

tolerations: []
  # - key: dedicated
  #   operator: Equal
  #   value: "management"
  #   effect: NoSchedule

affinity:
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #           - key: role
  #             operator: In
  #             values:
  #               - management
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app.kubernetes.io/instance
              operator: In
              values:
                - RELEASE_NAME
        topologyKey: kubernetes.io/hostname

controller:
  create: true

serviceAccount:
  create: true
  name: SERVICE_ACCOUNT

rbac:
  create: true
  pspEnabled: false

secretName: SECRET_NAME

ingress:
  enabled: ENABLE_INGRESS
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /v1/cert.pem
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

crd:
  create: true
  keep: false

networkPolicy: ENABLE_NETWORK_POLICY

securityContext:
  runAsUser: 1001
  fsGroup: 65534

priorityClassName: ""

serviceMonitor:
  create: ENABLE_SERVICE_MONITOR
  # interval:
  # labels:
  # namespace:
  # scrapeTimeout:

dashboards:
  # See https://github.com/helm/charts/tree/master/stable/grafana#configuration - `sidecar.dashboards.enabled`
  create: ENABLE_GRAFANA_SIDECAR_DASHBOARD
  # labels:
  # namespace: