---
controllerService:
  replicaCount: 2

  nodeSelector:
    kubernetes.io/os: linux

  podSecurityContext:
    fsGroup: 2011

  fsxPlugin:
    image:
      repository: amazon/aws-fsx-csi-driver
      tag: v0.4.0 # The chart version is not the same as the image version.
      pullPolicy: IfNotPresent

    extraArgs:
      - --logtostderr
      - --v=5

    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      runAsUser: 1011

    resources: {}
      # requests:
      #   cpu: 10m

  csiProvisioner:
    # image:
    #   repository: quay.io/k8scsi/csi-provisioner
    #   tag: v1.3.0
    #   pullPolicy: IfNotPresent

    extraArgs:
      - --timeout=5m
      - --v=5
      - --enable-leader-election
      - --leader-election-type=leases

    securityContext:
      capabilities:
        drop:
        - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1011

    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

# Daemonset
nodeService:
  podSecurityContext:
    fsGroup: 2011

  nodeSelector:
    kubernetes.io/os: linux

  fsxPlugin:
    image:
      repository: amazon/aws-fsx-csi-driver
      tag: v0.4.0 # The chart version is not the same as the image version.
      pullPolicy: IfNotPresent

    extraArgs:
      - --logtostderr
      - --v=5

    securityContext:
      privileged: true

    resources: {}
      # requests:
      #   cpu: 10m

  csiDriverRegistrar:
    # image:
    #   repository: quay.io/k8scsi/csi-node-driver-registrar
    #   tag: v1.1.0
    #   pullPolicy: IfNotPresent

    extraArgs:
      - --v=5

    securityContext: {}

    resources: {}
      # requests:
      #   cpu: 10m

  livenessProbe:
  #   image:
  #     repository: quay.io/k8scsi/livenessprobe
  #     tag: v1.1.0
  #     pullPolicy: Always

    resources:
      # requests:
      #   cpu: 10m

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  annotations:
    eks.amazonaws.com/role-arn: IAM_ROLE_ARN
  name: SERVICE_ACCOUNT