apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: fsx-csi-controller-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: aws-fsx-csi-driver-controller
      app.kubernetes.io/name: aws-fsx-csi-driver
