apiVersion: v1
kind: ServiceAccount
metadata:
  name: snapshot-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: snapshot-controller
  annotations:
      eks.amazonaws.com/role-arn: SNAPSHOT_IAM_ROLE_ARN
