apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: aws-load-balancer-controller-pdb
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: aws-load-balancer-controller
