apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: aws-load-balancer-controller
